/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.flink.table.runtime.dataview;

import org.apache.flink.annotation.Internal;

import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 * Runtime-owned bridge between generated DISTINCT code and batch-prefetchable state views.
 *
 * <p>Generated aggregation classes live in Flink's mutable code-generation class loader. Keeping
 * the interface test in generated bytecode can therefore make a valid runtime view appear
 * unsupported when the generated class resolves the interface through a different loader epoch.
 * This bridge is defined beside the view and performs the type test in the runtime class loader
 * that owns both {@link DistinctBatchStateMapView} and {@link BatchPrefetchableMapView}.
 */
@Internal
public final class DistinctBatchPrefetchSupport {

    private static final AtomicBoolean REPORTED_UNSUPPORTED_VIEW = new AtomicBoolean();
    private static final ThreadLocal<PreparedCapture> PREPARED_CAPTURE = new ThreadLocal<>();

    private DistinctBatchPrefetchSupport() {}

    /**
     * Returns a runtime-owned collection token, or {@code null} when the batch cannot reach the
     * configured useful-key threshold.
     *
     * <p>Generated code keeps this token for the complete collection scope. This performs the
     * class-loader-sensitive interface check once per outer-key batch instead of once per input
     * record, and lets it skip DISTINCT key extraction entirely for undersized groups.
     */
    public static Object beginSession(Object view, int expectedKeys) {
        BatchPrefetchableMapView<Object> prefetchable = asPrefetchable(view);
        return prefetchable != null && prefetchable.tryBeginPrefetchKeyCollection(expectedKeys)
                ? prefetchable
                : null;
    }

    public static void addSession(Object session, Object key) {
        asSession(session).addPrefetchKey(key);
    }

    public static boolean finishSession(Object session) throws Exception {
        PreparedCapture capture = PREPARED_CAPTURE.get();
        if (capture != null) {
            Object prepared = asSession(session).finishPreparedPrefetchKeyCollection();
            if (prepared != null) {
                capture.sessions.add(session);
                capture.prepared.add(prepared);
                return true;
            }
            return false;
        }
        return asSession(session).finishPrefetchKeyCollection();
    }

    public static Object finishPreparedSession(Object session) throws Exception {
        return asSession(session).finishPreparedPrefetchKeyCollection();
    }

    public static boolean installPreparedSession(Object session, Object prepared) throws Exception {
        return asSession(session).installPreparedPrefetch(prepared);
    }

    public static void abortPreparedSession(Object session, Object prepared) {
        if (session != null) {
            asSession(session).abortPreparedPrefetch(prepared);
        }
    }

    /** Captures existing generated prefetch calls as detached backend reads. */
    public static void beginPreparedCapture() {
        if (PREPARED_CAPTURE.get() != null) {
            throw new IllegalStateException("DISTINCT prepared capture is already active");
        }
        PREPARED_CAPTURE.set(new PreparedCapture());
    }

    /** Ends capture and returns a composite token, or {@code null} when no read was submitted. */
    public static Object endPreparedCapture() {
        PreparedCapture capture = PREPARED_CAPTURE.get();
        PREPARED_CAPTURE.remove();
        return capture == null || capture.prepared.isEmpty() ? null : capture;
    }

    /** Cancels every detached read accumulated by the current, not-yet-ended capture. */
    public static void abortPreparedCapture() {
        PreparedCapture capture = PREPARED_CAPTURE.get();
        PREPARED_CAPTURE.remove();
        abortPreparedCapture(capture);
    }

    /** Installs every prepared DISTINCT view for one outer key. */
    public static boolean installPreparedCapture(Object prepared) {
        if (!(prepared instanceof PreparedCapture)) {
            return false;
        }
        PreparedCapture capture = (PreparedCapture) prepared;
        boolean allInstalled = !capture.prepared.isEmpty();
        try {
            for (int i = 0; i < capture.prepared.size(); i++) {
                allInstalled &=
                        asSession(capture.sessions.get(i))
                                .installPreparedPrefetch(capture.prepared.get(i));
            }
            if (!allInstalled) {
                abortPreparedCapture(capture);
                return false;
            }
            return true;
        } catch (Exception failure) {
            // A speculative read is never authoritative. Clear any already-installed overlay and
            // let GroupAgg execute the established synchronous prefetch path for the whole key.
            abortPreparedCapture(capture);
            return false;
        }
    }

    /** Cancels or clears a composite token that will not be consumed. */
    public static void abortPreparedCapture(Object prepared) {
        if (!(prepared instanceof PreparedCapture)) {
            return;
        }
        PreparedCapture capture = (PreparedCapture) prepared;
        for (int i = 0; i < capture.prepared.size(); i++) {
            asSession(capture.sessions.get(i)).abortPreparedPrefetch(capture.prepared.get(i));
        }
    }

    public static void abortSession(Object session) {
        if (session != null) {
            asSession(session).abortPrefetchKeyCollection();
        }
    }

    public static void begin(Object view, int expectedKeys) {
        BatchPrefetchableMapView<Object> prefetchable = asPrefetchable(view);
        if (prefetchable != null) {
            prefetchable.beginPrefetchKeyCollection(expectedKeys);
        }
    }

    public static void add(Object view, Object key) {
        BatchPrefetchableMapView<Object> prefetchable = asPrefetchable(view);
        if (prefetchable != null) {
            prefetchable.addPrefetchKey(key);
        }
    }

    public static boolean finish(Object view) throws Exception {
        BatchPrefetchableMapView<Object> prefetchable = asPrefetchable(view);
        return prefetchable != null && prefetchable.finishPrefetchKeyCollection();
    }

    public static void abort(Object view) {
        BatchPrefetchableMapView<Object> prefetchable = asPrefetchable(view);
        if (prefetchable != null) {
            prefetchable.abortPrefetchKeyCollection();
        }
    }

    @SuppressWarnings("unchecked")
    private static BatchPrefetchableMapView<Object> asPrefetchable(Object view) {
        if (view instanceof BatchPrefetchableMapView) {
            return (BatchPrefetchableMapView<Object>) view;
        }
        if (view != null && REPORTED_UNSUPPORTED_VIEW.compareAndSet(false, true)) {
            System.err.printf(
                    "[CACHEKIT DISTINCT PREFETCH] unsupported view=%s viewLoader=%s supportLoader=%s%n",
                    view.getClass().getName(),
                    view.getClass().getClassLoader(),
                    DistinctBatchPrefetchSupport.class.getClassLoader());
        }
        return null;
    }

    @SuppressWarnings("unchecked")
    private static BatchPrefetchableMapView<Object> asSession(Object session) {
        if (!(session instanceof BatchPrefetchableMapView)) {
            throw new IllegalArgumentException("Invalid DISTINCT prefetch session token");
        }
        return (BatchPrefetchableMapView<Object>) session;
    }

    private static final class PreparedCapture {
        private final List<Object> sessions = new ArrayList<>();
        private final List<Object> prepared = new ArrayList<>();
    }
}
