/*
 * Licensed to the Apache Software Foundation (ASF) under one
 * or more contributor license agreements.  See the NOTICE file
 * distributed with this work for additional information
 * regarding copyright ownership.  The ASF licenses this file
 * to you under the Apache License, Version 2.0 (the
 * "License"); you may not use this file except in compliance
 * with the License.  You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.flink.table.runtime.dataview;

import org.apache.flink.annotation.Internal;
import org.apache.flink.runtime.state.internal.BatchPrefetchableMapState;
import org.apache.flink.streaming.api.operators.PipelinedBatchableKeyedFunction.BatchWindowPreparationResult;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.List;
import java.util.concurrent.atomic.AtomicBoolean;

/**
 * Runtime-owned bridge between generated DISTINCT code and batch-prefetchable state views.
 *
 * <p>Generated aggregation classes live in Flink's mutable code-generation class loader. Keeping
 * the interface test in generated bytecode can therefore make a valid runtime view appear
 * unsupported when the generated class resolves the interface through a different loader epoch.
 * This bridge is defined beside the view and performs the type test in the runtime class loader
 * that owns both {@link DistinctBatchStateMapView} and {@link BatchPrefetchableMapView}.
 */
@Internal
public final class DistinctBatchPrefetchSupport {

    private static final AtomicBoolean REPORTED_UNSUPPORTED_VIEW = new AtomicBoolean();
    private static final ThreadLocal<CaptureContext> PREPARED_CAPTURE =
            ThreadLocal.withInitial(CaptureContext::new);
    private static final ThreadLocal<PreparedWaveWorkspace> PREPARED_WAVE_WORKSPACE =
            ThreadLocal.withInitial(PreparedWaveWorkspace::new);
    private static final ThreadLocal<PreparedWaveDiagnostics> PREPARED_WAVE_DIAGNOSTICS =
            ThreadLocal.withInitial(PreparedWaveDiagnostics::new);

    private DistinctBatchPrefetchSupport() {}

    /**
     * Returns a runtime-owned collection token, or {@code null} when the batch cannot reach the
     * configured useful-key threshold.
     *
     * <p>Generated code keeps this token for the complete collection scope. This performs the
     * class-loader-sensitive interface check once per outer-key batch instead of once per input
     * record, and lets it skip DISTINCT key extraction entirely for undersized groups.
     */
    public static Object beginSession(Object view, int expectedKeys) {
        BatchPrefetchableMapView<Object> prefetchable = asPrefetchable(view);
        return prefetchable != null && prefetchable.tryBeginPrefetchKeyCollection(expectedKeys)
                ? prefetchable
                : null;
    }

    public static void addSession(Object session, Object key) {
        asSession(session).addPrefetchKey(key);
    }

    public static boolean finishSession(Object session) throws Exception {
        CaptureContext context = PREPARED_CAPTURE.get();
        if (context.active != null) {
            PreparedCapture active = context.active;
            active.acceptedSessions++;
            Object prepared = asSession(session).finishPreparedPrefetchKeyCollection();
            if (prepared != null) {
                active.sessions.add(session);
                active.prepared.add(prepared);
                return true;
            }
            active.preparationFailed = true;
            return false;
        }
        return asSession(session).finishPrefetchKeyCollection();
    }

    public static Object finishPreparedSession(Object session) throws Exception {
        return asSession(session).finishPreparedPrefetchKeyCollection();
    }

    public static boolean installPreparedSession(Object session, Object prepared) throws Exception {
        return asSession(session).installPreparedPrefetch(prepared);
    }

    public static void abortPreparedSession(Object session, Object prepared) {
        if (session != null) {
            asSession(session).abortPreparedPrefetch(prepared);
        }
    }

    /** Captures existing generated prefetch calls as detached backend reads. */
    public static void beginPreparedCapture() {
        CaptureContext context = PREPARED_CAPTURE.get();
        if (context.active != null) {
            throw new IllegalStateException("DISTINCT prepared capture is already active");
        }
        PreparedCapture capture = context.available.pollFirst();
        if (capture == null) {
            capture = new PreparedCapture();
        }
        capture.resetForLease();
        context.active = capture;
    }

    /** Ends capture and returns a composite token, including a rejected-session no-op token. */
    public static Object endPreparedCapture() {
        CaptureContext context = PREPARED_CAPTURE.get();
        PreparedCapture capture = context.active;
        context.active = null;
        // A capture with no accepted sessions is a successful no-op. This happens when generated
        // DISTINCT code rejects an undersized group before scanning its keys. Keep it distinct
        // from an accepted session whose backend preparation failed, which must retain the
        // established synchronous fallback at consumption time.
        return capture;
    }

    /** Cancels every detached read accumulated by the current, not-yet-ended capture. */
    public static void abortPreparedCapture() {
        CaptureContext context = PREPARED_CAPTURE.get();
        PreparedCapture capture = context.active;
        context.active = null;
        abortPreparedCapture(capture);
    }

    /** Installs every prepared DISTINCT view for one outer key. */
    public static boolean installPreparedCapture(Object prepared) {
        if (!(prepared instanceof PreparedCapture)) {
            return false;
        }
        PreparedCapture capture = (PreparedCapture) prepared;
        if (!capture.leased
                || capture.preparationFailed
                || capture.prepared.size() != capture.acceptedSessions) {
            abortPreparedCapture(capture);
            return false;
        }
        boolean allInstalled = true;
        try {
            for (int i = 0; i < capture.prepared.size(); i++) {
                allInstalled &=
                        asSession(capture.sessions.get(i))
                                .installPreparedPrefetch(capture.prepared.get(i));
            }
            if (!allInstalled) {
                abortPreparedCapture(capture);
                return false;
            }
            releaseCapture(capture);
            return true;
        } catch (Exception failure) {
            // A speculative read is never authoritative. Clear any already-installed overlay and
            // let GroupAgg execute the established synchronous prefetch path for the whole key.
            abortPreparedCapture(capture);
            return false;
        }
    }

    /** Cancels or clears a composite token that will not be consumed. */
    public static void abortPreparedCapture(Object prepared) {
        if (!(prepared instanceof PreparedCapture)) {
            return;
        }
        PreparedCapture capture = (PreparedCapture) prepared;
        if (!capture.leased) {
            return;
        }
        for (int i = 0; i < capture.prepared.size(); i++) {
            asSession(capture.sessions.get(i)).abortPreparedPrefetch(capture.prepared.get(i));
        }
        releaseCapture(capture);
    }

    /**
     * Executes one bounded, single-owner read wave for a set of prepared outer-key captures.
     *
     * <p>No capture is consumed or installed here. Each generated DISTINCT view is treated as an
     * independent column across the outer-key cohort: tokens for view 0 are waved together, then
     * tokens for view 1, and so on. This is required for queries such as q15 whose generated
     * aggregate owns several DISTINCT MapStates per outer key. Unsupported capture shapes are
     * rejected before any wave executes. A heavy or otherwise ineligible column remains on its
     * established per-group path without preventing an eligible sibling column from executing.
     */
    public static BatchWindowPreparationResult executePreparedWave(
            Object[] preparedCaptures, int count) throws Exception {
        if (preparedCaptures == null || count < 2 || count > preparedCaptures.length) {
            return BatchWindowPreparationResult.UNSUPPORTED;
        }
        PreparedWaveWorkspace workspace = PREPARED_WAVE_WORKSPACE.get();
        PreparedWaveDiagnostics diagnostics = PREPARED_WAVE_DIAGNOSTICS.get();
        diagnostics.cohortAttempts++;
        diagnostics.captures += count;
        int viewCount = -1;
        try {
            for (int index = 0; index < count; index++) {
                Object candidate = preparedCaptures[index];
                if (!(candidate instanceof PreparedCapture)) {
                    diagnostics.invalidCaptures++;
                    return recordWaveResult(diagnostics, BatchWindowPreparationResult.UNSUPPORTED);
                }
                PreparedCapture capture = (PreparedCapture) candidate;
                if (!capture.leased
                        || capture.preparationFailed
                        || capture.prepared.size() != capture.acceptedSessions
                        || capture.sessions.size() != capture.prepared.size()) {
                    diagnostics.rejectedCaptures++;
                    return recordWaveResult(
                            diagnostics, BatchWindowPreparationResult.RETRY_AFTER_COHORT);
                }
                if (viewCount < 0) {
                    viewCount = capture.prepared.size();
                    diagnostics.sessionColumns += viewCount;
                    if (viewCount > 1) {
                        diagnostics.multiViewCohorts++;
                    }
                    workspace.prepare(viewCount);
                } else if (capture.prepared.size() != viewCount) {
                    diagnostics.cardinalityMismatches++;
                    return recordWaveResult(
                            diagnostics, BatchWindowPreparationResult.RETRY_AFTER_COHORT);
                }
                for (int view = 0; view < viewCount; view++) {
                    BatchPrefetchableMapView<Object> session =
                            asSession(capture.sessions.get(view));
                    Object viewPrepared = capture.prepared.get(view);
                    Object backendPrepared = session.preparedBackendValueForWave(viewPrepared);
                    if (backendPrepared == null && session.isPreparedWaveNoOp(viewPrepared)) {
                        diagnostics.noOpTokens++;
                        continue;
                    }
                    if (!(backendPrepared instanceof BatchPrefetchableMapState.PreparedValues)) {
                        diagnostics.invalidBackendTokens++;
                        return recordWaveResult(
                                diagnostics, BatchWindowPreparationResult.UNSUPPORTED);
                    }
                    BatchPrefetchableMapState.PreparedValues preparedValue =
                            (BatchPrefetchableMapState.PreparedValues) backendPrepared;
                    BatchPrefetchableMapState.PreparedValues.WaveParticipation participation =
                            preparedValue.waveParticipation();
                    if (participation
                            == BatchPrefetchableMapState.PreparedValues.WaveParticipation
                                    .DISABLED) {
                        diagnostics.disabledTokens++;
                        return recordWaveResult(
                                diagnostics, BatchWindowPreparationResult.UNSUPPORTED);
                    }
                    workspace.sawBackendToken[view] = true;
                    if (participation
                            == BatchPrefetchableMapState.PreparedValues.WaveParticipation
                                    .INELIGIBLE) {
                        diagnostics.ineligibleTokens++;
                        workspace.eligible[view] = false;
                        continue;
                    }
                    Object currentOwner = preparedValue.waveOwner();
                    if (currentOwner == null) {
                        diagnostics.nullOwnerTokens++;
                        workspace.eligible[view] = false;
                        continue;
                    }
                    if (workspace.owners[view] != null && workspace.owners[view] != currentOwner) {
                        diagnostics.ownerMismatchTokens++;
                        workspace.eligible[view] = false;
                        continue;
                    }
                    diagnostics.eligibleTokens++;
                    workspace.owners[view] = currentOwner;
                    workspace.values.get(view).add(preparedValue);
                }
            }
            if (viewCount <= 0) {
                diagnostics.emptyCohorts++;
                return recordWaveResult(
                        diagnostics, BatchWindowPreparationResult.RETRY_AFTER_COHORT);
            }
            boolean executed = false;
            for (int view = 0; view < viewCount; view++) {
                ArrayList<BatchPrefetchableMapState.PreparedValues> values =
                        workspace.values.get(view);
                if (!workspace.sawBackendToken[view]
                        || !workspace.eligible[view]
                        || values.size() < 2) {
                    diagnostics.skippedColumns++;
                    if (workspace.sawBackendToken[view]
                            && workspace.eligible[view]
                            && values.size() < 2) {
                        diagnostics.insufficientColumns++;
                    }
                    continue;
                }
                diagnostics.columnWaveAttempts++;
                diagnostics.columnWaveGroups += values.size();
                try {
                    if (values.get(0).executeWave(values)) {
                        diagnostics.columnWavesExecuted++;
                        executed = true;
                    } else {
                        diagnostics.columnWavesRejected++;
                    }
                } catch (Exception | LinkageError ignored) {
                    diagnostics.columnWaveFailures++;
                    // A speculative wave is never authoritative. Backend implementations publish
                    // only after validating the complete view-column, so every capture retains
                    // its established per-group fallback for any rejected sibling column.
                }
            }
            return recordWaveResult(
                    diagnostics,
                    executed
                            ? BatchWindowPreparationResult.EXECUTED
                            : BatchWindowPreparationResult.RETRY_AFTER_COHORT);
        } finally {
            workspace.clear();
        }
    }

    private static BatchWindowPreparationResult recordWaveResult(
            PreparedWaveDiagnostics diagnostics, BatchWindowPreparationResult result) {
        if (result == BatchWindowPreparationResult.EXECUTED) {
            diagnostics.cohortsExecuted++;
        } else if (result == BatchWindowPreparationResult.RETRY_AFTER_COHORT) {
            diagnostics.cohortsRetried++;
        } else {
            diagnostics.cohortsUnsupported++;
        }
        if (diagnostics.cohortAttempts % 5000L == 1L) {
            diagnostics.report();
        }
        return result;
    }

    public static void abortSession(Object session) {
        if (session != null) {
            asSession(session).abortPrefetchKeyCollection();
        }
    }

    public static void begin(Object view, int expectedKeys) {
        BatchPrefetchableMapView<Object> prefetchable = asPrefetchable(view);
        if (prefetchable != null) {
            prefetchable.beginPrefetchKeyCollection(expectedKeys);
        }
    }

    public static void add(Object view, Object key) {
        BatchPrefetchableMapView<Object> prefetchable = asPrefetchable(view);
        if (prefetchable != null) {
            prefetchable.addPrefetchKey(key);
        }
    }

    public static boolean finish(Object view) throws Exception {
        BatchPrefetchableMapView<Object> prefetchable = asPrefetchable(view);
        return prefetchable != null && prefetchable.finishPrefetchKeyCollection();
    }

    public static void abort(Object view) {
        BatchPrefetchableMapView<Object> prefetchable = asPrefetchable(view);
        if (prefetchable != null) {
            prefetchable.abortPrefetchKeyCollection();
        }
    }

    @SuppressWarnings("unchecked")
    private static BatchPrefetchableMapView<Object> asPrefetchable(Object view) {
        if (view instanceof BatchPrefetchableMapView) {
            return (BatchPrefetchableMapView<Object>) view;
        }
        if (view != null && REPORTED_UNSUPPORTED_VIEW.compareAndSet(false, true)) {
            System.err.printf(
                    "[CACHEKIT DISTINCT PREFETCH] unsupported view=%s viewLoader=%s supportLoader=%s%n",
                    view.getClass().getName(),
                    view.getClass().getClassLoader(),
                    DistinctBatchPrefetchSupport.class.getClassLoader());
        }
        return null;
    }

    @SuppressWarnings("unchecked")
    private static BatchPrefetchableMapView<Object> asSession(Object session) {
        if (!(session instanceof BatchPrefetchableMapView)) {
            throw new IllegalArgumentException("Invalid DISTINCT prefetch session token");
        }
        return (BatchPrefetchableMapView<Object>) session;
    }

    private static void releaseCapture(PreparedCapture capture) {
        if (capture == null || !capture.leased) {
            return;
        }
        capture.sessions.clear();
        capture.prepared.clear();
        capture.acceptedSessions = 0;
        capture.preparationFailed = false;
        capture.leased = false;
        PREPARED_CAPTURE.get().available.addLast(capture);
    }

    private static final class CaptureContext {
        private final ArrayDeque<PreparedCapture> available = new ArrayDeque<>();
        private PreparedCapture active;
    }

    private static final class PreparedWaveWorkspace {
        private final List<ArrayList<BatchPrefetchableMapState.PreparedValues>> values =
                new ArrayList<>();
        private Object[] owners = new Object[2];
        private boolean[] eligible = new boolean[2];
        private boolean[] sawBackendToken = new boolean[2];
        private int viewCount;

        private void prepare(int requiredViews) {
            if (owners.length < requiredViews) {
                owners = new Object[requiredViews];
                eligible = new boolean[requiredViews];
                sawBackendToken = new boolean[requiredViews];
            }
            while (values.size() < requiredViews) {
                values.add(new ArrayList<>());
            }
            viewCount = requiredViews;
            for (int view = 0; view < requiredViews; view++) {
                values.get(view).clear();
                owners[view] = null;
                eligible[view] = true;
                sawBackendToken[view] = false;
            }
        }

        private void clear() {
            for (int view = 0; view < viewCount; view++) {
                values.get(view).clear();
                owners[view] = null;
                eligible[view] = false;
                sawBackendToken[view] = false;
            }
            viewCount = 0;
        }
    }

    /** Thread-confined counters keep the experimental wave hot path allocation and CAS free. */
    private static final class PreparedWaveDiagnostics {
        private long cohortAttempts;
        private long cohortsExecuted;
        private long cohortsRetried;
        private long cohortsUnsupported;
        private long captures;
        private long multiViewCohorts;
        private long sessionColumns;
        private long invalidCaptures;
        private long rejectedCaptures;
        private long cardinalityMismatches;
        private long noOpTokens;
        private long invalidBackendTokens;
        private long disabledTokens;
        private long ineligibleTokens;
        private long nullOwnerTokens;
        private long ownerMismatchTokens;
        private long eligibleTokens;
        private long skippedColumns;
        private long insufficientColumns;
        private long columnWaveAttempts;
        private long columnWavesExecuted;
        private long columnWavesRejected;
        private long columnWaveFailures;
        private long columnWaveGroups;
        private long emptyCohorts;

        private void report() {
            System.err.printf(
                    "[CACHEKIT DISTINCT WAVE ORCHESTRATOR] thread=%s cohortAttempts=%d cohortsExecuted=%d cohortsRetried=%d cohortsUnsupported=%d captures=%d multiViewCohorts=%d sessionColumns=%d invalidCaptures=%d rejectedCaptures=%d cardinalityMismatches=%d noOpTokens=%d invalidBackendTokens=%d disabledTokens=%d ineligibleTokens=%d nullOwnerTokens=%d ownerMismatchTokens=%d eligibleTokens=%d skippedColumns=%d insufficientColumns=%d columnWaveAttempts=%d columnWavesExecuted=%d columnWavesRejected=%d columnWaveFailures=%d columnWaveGroups=%d emptyCohorts=%d%n",
                    Thread.currentThread().getName(),
                    cohortAttempts,
                    cohortsExecuted,
                    cohortsRetried,
                    cohortsUnsupported,
                    captures,
                    multiViewCohorts,
                    sessionColumns,
                    invalidCaptures,
                    rejectedCaptures,
                    cardinalityMismatches,
                    noOpTokens,
                    invalidBackendTokens,
                    disabledTokens,
                    ineligibleTokens,
                    nullOwnerTokens,
                    ownerMismatchTokens,
                    eligibleTokens,
                    skippedColumns,
                    insufficientColumns,
                    columnWaveAttempts,
                    columnWavesExecuted,
                    columnWavesRejected,
                    columnWaveFailures,
                    columnWaveGroups,
                    emptyCohorts);
        }
    }

    private static final class PreparedCapture {
        private final List<Object> sessions = new ArrayList<>();
        private final List<Object> prepared = new ArrayList<>();
        private int acceptedSessions;
        private boolean preparationFailed;
        private boolean leased;

        private void resetForLease() {
            if (leased) {
                throw new IllegalStateException("DISTINCT prepared capture is already leased");
            }
            sessions.clear();
            prepared.clear();
            acceptedSessions = 0;
            preparationFailed = false;
            leased = true;
        }
    }
}
